import { Header } from "@/components/header";
import { Form } from "@/components/home/Form";
import { ChemicalElementProvider, useChemicalElement } from "@/context/ChemicalElementProvider";
import Head from "next/head";
import Image from "next/image";

const element_properties_dictionary = {
	nome: "Nome do elemento: ",
	abr: "Abreviação: ",
	massa: "Massa atômica: ",
	num_atomico: "Número atômico: ",
	num_protons: "Número de prótons: ",
	num_neutrons: "Número de nêutrons: ",
} as Record<string, string>;

export default function Home() {
	const { element } = useChemicalElement();

	console.log("element: ", element);

	return (
		<>
			<Head>
				<title>Distribuição Eletrônica</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/atom.png" />
			</Head>

			<main className="m-auto min-h-screen w-full bg-white">
				<Header />

				<div className="m-auto max-w-[1100px]">
					<Form />

					{element?.nome && (
						<>
							<div className="my-6 h-[1px] w-full bg-gray-200 shadow-md" />

							<div className="flex justify-between gap-8">
								<div className="flex w-full flex-col gap-2 rounded-lg bg-blue-400 bg-opacity-50 p-4 shadow-lg">
									<h3 className="text-xl font-medium">Classificação por camadas</h3>

									<div>
										<p>K: 2</p>
										<p>L: 8</p>
										<p>M: 18</p>
										<p>N: 32</p>
									</div>
								</div>

								<div className="flex w-full flex-col gap-2 rounded-lg bg-blue-400 bg-opacity-50 p-4 shadow-lg">
									<h3 className="text-xl font-medium">Classificação por subníveis</h3>

									<div className="flex gap-2">
										<span>1s²</span>
										<span>2s²</span>
										<span>2p⁶</span>
										<span>3s²</span>
										<span>3p⁶</span>
									</div>
								</div>
							</div>

							<div className="mt-6 flex w-full flex-col gap-2 rounded-lg bg-blue-400 bg-opacity-50 p-4 shadow-lg">
								<h3 className="text-xl font-medium">Propriedades do Elemento</h3>

								<div>
									{Object.entries(element).map(([key, value]) => {
										if (value === null || value === 0) return null;

										return (
											<p key={value}>
												{element_properties_dictionary[key]} {value}
											</p>
										);
									})}
								</div>
							</div>
						</>
					)}
				</div>

				{/* <div>
						<h2>O que é a Distribuição Eletrônica?</h2>

						<p>
							A distribuição eletrônica representa a forma como os elétrons se organizam na
							eletrosfera do elemento químico.
						</p>

						<h2>Como é a estrutura do átomo?</h2>
						<p>
							O <strong>átomo</strong> é dividido basicamente em duas regiões: O{" "}
							<strong>núcleo</strong> e a<strong>eletrosfera.</strong> <br />O <strong>núcleo</strong>{" "}
							é composto pelos <strong>protóns</strong> positiva e os <strong>neutrôns</strong> neutra
							Os neutrôns são essencias no núcleo do átomo para separar os prótons, pois elementos com
							cargas iguais se repelem, então jamais conseguiriam permanecer juntos no núcleo atômico.
							O núcleo também é responsável por aproximadamente toda massa do átomo (em vista de que a
							massa da eletrosfera é insignificante.) <br />A <strong>eletrosfera</strong> consiste em
							um espaço majoritariamente vazio (este que é aproximadamente 100.000 vezes o tamanho do
							núcleo) que comporta os elétrons do átomo, que possuem cargas <span>negativas.</span> Os
							elétrons nessa eletrosfera são divididos em camadas, como podemos ver na imagem abaixo:
							<Image
								width={300}
								height={200}
								src="/images/diagrama_linus_pauling.webp"
								alt="camadas do elétron"
							/>{" "}
							<br />E dentro dessas camadas, são divididos em subníveis, que será mostrado logo{" "}
							<a href="#pauling">abaixo</a>.
						</p>

						<h2>Diagrama de Pauling</h2>
						<p>
							Anteriormente a Pauling, sabia-se que os elétrons eram distribuídos em camadas, porém
							não havia conhecimento de como eles se organizavam dentro dessas camadas. Pauling
							conseguiu com seus estudos, descobrir que a forma com que os elétrons se organizavam
							eram em subníveis, e daí se criou o famoso Diagrama de Linus Pauling. <br />
							Ao usar o Diagrama de Pauling, um dos erros mais cometidos é de seguir horizontalmente a
							ordem, sendo que a forma correta seria de acordo com a imagem abaixo: <br />
							<img
								src="https://s3-sa-east-1.amazonaws.com/manual-do-enem-test/aae99e4f0cbe47879c002900bfc77156-247.png"
								width="300px"
								alt="Diagrama de Linus Pauling"
							/>{" "}
							<br />
							Mas por que a ordem tem que ser seguida diagonalmente? <br />
							Isso ocorre pois ao fazermos a distribuição eletrônica, estamos organizando os subníveis
							em forma crescente de energia, e devido a{" "}
							<a href="https://www.youtube.com/watch?v=sMt5Dcex0kg" target="_blank">
								órbita dos elétrons
							</a>
							, pode acontecer de um elétron presente numa camada maior, tenha menos energia de um
							presente em uma camada menor.
						</p>
					</div> */}
			</main>
		</>
	);
}
